### PR TITLE
Updated WFMU station url

### PR DESCRIPTION
**Pull request by damassi**
Updated url to resolvable location.  The old .pls was invalid!

### CODE REVIEW

**Comment by substack** [comment]
All merged, if a bit late.

**Comment by damassi** [comment]
Tuner is my favorite module of them all!

**Comment by substack** [comment]
I've added you as a collaborator on npm and github so you won't have to wait so long next time!

**Comment by damassi** [comment]
Awesome, thanks so much.  I'll make sure to update it as I come along new items.  :+1:

**Pull request closed without merging**
